### PR TITLE
Milestone 2 : Implement add and remove functionalities

### PR DESCRIPTION
**Pull request by Lizdev-05**
In this milestone, I achieved the following...

- Set todo items to the local storage
- Get todo items from the local storage
- Display add items to the UI
- Remove filtered items from the UI
- Implement the editing function
- Check the box for the completed items

### CODE REVIEW

**Comment by gtekle** [comment]
Hi @Lizdev-05 
Would you please add a professional ReadMe before I start reviewing as well?
Thanks

**Review by gtekle — CHANGES_REQUESTED** [review]
Hi @Lizdev-05 :wave: , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has not professional ReadMe. Kindly add a professional ReadMe as per the [template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by Microverse.
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Lizdev-05** [comment]
Okay, thank you for calling my attention to it. It escaped my mind to edit
the default Readme. I will implement it in the morning.

**Review by elyor-doniyorov — APPROVED** [review]
Hi @Lizdev-05, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Descriptive PR title and description
✅ Descriptive Readme file

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
